# Importing Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

# Importing Dataset

In [2]:
dataset = pd.read_csv('Data.csv')
#Any dataset - Features(columns on which you will use to predict, or independant variables) and dependant variable(predicted variable)
#Features usually in first columns, with dependent variable in last column
X = dataset.iloc[:, :-1].values #creating matrix of feature, by taking all rows and all columns expcept last(-1)
y = dataset.iloc[:, -1].values  #creating dependent variable vector

In [3]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking Care of Missing Data

In [5]:
#Cannot have missing data or can cause errors in training the model. Deleting rows of issing data only an option with
# very large datasets where deleted data is 1% or less

#Replace missing salary info by taking average(classic method)

imputer = SimpleImputer(missing_values=np.nan, strategy='mean') #create Object of SimpleImputer
imputer.fit(X[:, 1:3]) #Fit(calculate mean values) from dataset matrix, (in general, into all numerical columns to make sure all data is corrected)
X[:, 1:3] = imputer.transform(X[:, 1:3]) #Create new X matrix with transformed values


In [6]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding Categorical Features

In [7]:
#It could could be confusing to model if encoding countries like 1,2,3 because could interprut as ordinal data. 
#One hot encoding will ensure interpreted as nominal categorical data.

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0] )], remainder='passthrough')
X = np.array(ct.fit_transform(X)) #fit and transform X matrix into numpy array using encoding settings above. Training will expect numpy arrays

In [8]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


## Encoding Dependent Variable

In [9]:
le = LabelEncoder()
y = le.fit_transform(y) # does not to be numpy array, because precited feature of single vector

In [10]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting dataset into Train and Test sets

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=1) #recommend 80-20 split, taken randomly

In [12]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [13]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [14]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [15]:
print(y_test)

[0 1]


## Feature Scaling

In [16]:
#FEATURE SCALING MUCH BE COMPLETED AFTER SPLITTING THE DATASET
#Putting feature all on the same scale, to avoid some features being domianted by others such that ML model does not 
#include the dominated feature. This is not necessary for all model preprocessing

#x_standardization : (x-mean(x))/SD(x)           resulting in values b/w -3 and +3
   #This technique will work at all times

#X_normalization :   (x-min(x))/(max(x)-min(x))  resulting in values b/x 0 and 1
   #Recommended when normal distro in most features
    

#IMPORTANT: Apply feature scaling technique to only X_train using mean(X_train) and SD(X_train) and then use these same values to 
            #apply scaler to X_test. This is because we do not have the right to scale X_test using its matrix values. 

           
sc = StandardScaler()
#Apply Standard Scaler to dummy variables?
#Answer: NO, the dummy variables already are wihtin the same range, which the point of standardization

X_train[:, 3:] = sc.fit_transform(X_train[:, 3:]) #fit(calculate mean(X) and SD(X)) and transform(apply to X matrix)
X_test[:, 3:]  = sc.transform(X_test[:, 3:])      #ONLY transform X_test using same scaler from X_train. Do not create new scaler
                                                  #fit for X_test, as X_test is "unknown" data. 


In [17]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [18]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
